"""
Transactional email sender for org invites.

Uses the Resend HTTP API directly via httpx — no SDK dependency. The only
email v1 sends is the invite, so a single function covers it. When more
transactional emails ship (digests, weekly recaps), grow this file or
move to a templates/ module.

The actual magic link is generated by Supabase Auth via
`auth.admin.generate_link(...)` upstream of this call; we just ferry it
to the recipient's inbox.

Resend dashboard: https://resend.com — manage domain verification, view
delivery logs, and configure templates if a richer formatting layer is
ever needed.
"""
from __future__ import annotations

import html
import httpx

from app.config import Settings


class EmailDeliveryError(RuntimeError):
    """Raised when Resend returns a non-2xx response. The caller should
    stamp the error message on `org_invites.last_delivery_error` so the
    owner sees it in the team settings page and can retry."""


def _safe_link(url: str) -> str:
    """Allow only http(s) URLs in href= attributes. Anything else
    becomes the empty string so an attacker who somehow got a
    `javascript:`-scheme URL into the magic_link slot can't fire it."""
    if not isinstance(url, str):
        return ""
    if not (url.startswith("https://") or url.startswith("http://")):
        return ""
    return html.escape(url, quote=True)


def _render_invite_html(*, magic_link: str, org_name: str, inviter_name: str) -> str:
    """Inline HTML template. Every interpolated value is HTML-escaped —
    org_name and inviter_name are owner-controlled and could otherwise
    contain `<script>`, `"><a href=…>` payloads, or break out of HTML
    attributes to inject a phishing link."""
    org_name_safe = html.escape(org_name)
    inviter_safe = html.escape(inviter_name)
    href_safe = _safe_link(magic_link)
    return f"""\
<!DOCTYPE html>
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 560px; margin: 32px auto; padding: 24px; color: #1a1a1a;">
  <h1 style="font-size: 20px; margin: 0 0 16px;">You've been invited to {org_name_safe}</h1>
  <p style="font-size: 15px; line-height: 1.5; margin: 0 0 16px;">
    {inviter_safe} added you to their Backroom workspace, where their AI team
    helps run their YouTube channel — strategy, publishing, community, sponsors.
  </p>
  <p style="font-size: 15px; line-height: 1.5; margin: 0 0 24px;">
    Click below to set up your account and join.
  </p>
  <p style="margin: 24px 0;">
    <a href="{href_safe}"
       style="background: #6366F1; color: white; padding: 12px 20px; border-radius: 8px; text-decoration: none; font-weight: 600; font-size: 15px;">
      Join {org_name_safe}
    </a>
  </p>
  <p style="font-size: 13px; color: #6b7280; margin: 24px 0 0;">
    Or paste this link into your browser:<br>
    <a href="{href_safe}" style="color: #6366F1; word-break: break-all;">{href_safe}</a>
  </p>
</body>
</html>"""


def _render_invite_text(*, magic_link: str, org_name: str, inviter_name: str) -> str:
    # text/plain — no escaping needed, but strip newlines from the
    # owner-controlled fields so they can't inject extra headers via
    # the subject line (the subject is built upstream from these too).
    safe_org = (org_name or "").replace("\r", "").replace("\n", " ").strip()
    safe_inviter = (inviter_name or "").replace("\r", "").replace("\n", " ").strip()
    return (
        f"{safe_inviter} invited you to {safe_org} on Backroom.\n\n"
        f"Set up your account and join here:\n{magic_link}\n"
    )


async def send_invite_email(
    *,
    to: str,
    magic_link: str,
    org_name: str,
    inviter_name: str,
    settings: Settings,
) -> str:
    """Send the invite email through Resend.

    Returns the Resend message id on success. Raises EmailDeliveryError
    on Resend non-2xx or network failure — the caller stamps the error
    on the org_invites row.
    """
    if not settings.resend_api_key:
        raise EmailDeliveryError("RESEND_API_KEY not configured")

    # Strip newlines/control chars from owner-controlled fields before
    # using them in the email subject — RFC 5322 forbids CR/LF in
    # subject lines, and an attacker who controls org_name could
    # otherwise inject extra headers via header injection.
    safe_subj_org = (org_name or "").replace("\r", "").replace("\n", " ").strip()
    safe_subj_inviter = (inviter_name or "").replace("\r", "").replace("\n", " ").strip()
    payload = {
        "from": settings.email_from,
        "to": [to],
        "subject": f"{safe_subj_inviter} invited you to {safe_subj_org} on Backroom",
        "html": _render_invite_html(magic_link=magic_link, org_name=org_name, inviter_name=inviter_name),
        "text": _render_invite_text(magic_link=magic_link, org_name=org_name, inviter_name=inviter_name),
    }

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            resp = await client.post(
                "https://api.resend.com/emails",
                headers={
                    "Authorization": f"Bearer {settings.resend_api_key}",
                    "Content-Type": "application/json",
                },
                json=payload,
            )
    except httpx.HTTPError as e:
        raise EmailDeliveryError(f"network: {e}") from e

    if resp.status_code >= 400:
        # Resend returns {"message": "...", "name": "..."} on errors.
        # The error message gets stored on org_invites.last_delivery_error
        # and rendered in the team UI, so truncate + strip control chars
        # to keep it from being a content-injection vector if Resend ever
        # echoes user-supplied content back.
        try:
            err = resp.json()
            msg = err.get("message") or err.get("name") or resp.text
        except Exception:
            msg = resp.text or f"HTTP {resp.status_code}"
        msg = (msg or "")[:200].replace("\r", " ").replace("\n", " ").strip()
        raise EmailDeliveryError(f"resend {resp.status_code}: {msg}")

    body = resp.json()
    return body.get("id") or ""
